[2024-07-05T21:55:00.245+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-05T21:55:00.255+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: podcast_summary.download_episodes manual__2024-07-05T21:54:57.078654+00:00 [queued]>
[2024-07-05T21:55:00.258+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: podcast_summary.download_episodes manual__2024-07-05T21:54:57.078654+00:00 [queued]>
[2024-07-05T21:55:00.258+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-05T21:55:00.264+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): download_episodes> on 2024-07-05 21:54:57.078654+00:00
[2024-07-05T21:55:00.268+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=14404) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-05T21:55:00.272+0000] {standard_task_runner.py:63} INFO - Started process 14408 to run task
[2024-07-05T21:55:00.271+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'podcast_summary', 'download_episodes', 'manual__2024-07-05T21:54:57.078654+00:00', '--job-id', '140', '--raw', '--subdir', 'DAGS_FOLDER/podcast_summary.py', '--cfg-path', '/tmp/tmp2fzqe18u']
[2024-07-05T21:55:00.277+0000] {standard_task_runner.py:91} INFO - Job 140: Subtask download_episodes
[2024-07-05T21:55:00.304+0000] {task_command.py:426} INFO - Running <TaskInstance: podcast_summary.download_episodes manual__2024-07-05T21:54:57.078654+00:00 [running]> on host 4f6b501c5f6b
[2024-07-05T21:55:00.354+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='podcast_summary' AIRFLOW_CTX_TASK_ID='download_episodes' AIRFLOW_CTX_EXECUTION_DATE='2024-07-05T21:54:57.078654+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-05T21:54:57.078654+00:00'
[2024-07-05T21:55:00.355+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-05T21:55:00.355+0000] {logging_mixin.py:188} INFO - the-wages-vs-inflation-horse-race.mp3
[2024-07-05T21:55:00.355+0000] {logging_mixin.py:188} INFO - episodes/the-wages-vs-inflation-horse-race.mp3
[2024-07-05T21:55:00.355+0000] {logging_mixin.py:188} INFO - Downloading the-wages-vs-inflation-horse-race.mp3
[2024-07-05T21:55:02.816+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-05T21:55:02.819+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/podcast_summary.py", line 70, in download_episodes
    with open(audio_path, "wb+") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'episodes/the-wages-vs-inflation-horse-race.mp3'
[2024-07-05T21:55:02.839+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=podcast_summary, task_id=download_episodes, run_id=manual__2024-07-05T21:54:57.078654+00:00, execution_date=20240705T215457, start_date=20240705T215500, end_date=20240705T215502
[2024-07-05T21:55:02.853+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 140 for task download_episodes ([Errno 2] No such file or directory: 'episodes/the-wages-vs-inflation-horse-race.mp3'; 14408)
[2024-07-05T21:55:02.878+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-05T21:55:02.904+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-05T21:55:02.905+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
