[2024-07-04T21:46:24.058+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-04T21:46:24.069+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: podcast_summary.create_table_sqlite manual__2024-07-04T21:46:22.663158+00:00 [queued]>
[2024-07-04T21:46:24.073+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: podcast_summary.create_table_sqlite manual__2024-07-04T21:46:22.663158+00:00 [queued]>
[2024-07-04T21:46:24.073+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-04T21:46:24.079+0000] {taskinstance.py:2330} INFO - Executing <Task(SqliteOperator): create_table_sqlite> on 2024-07-04 21:46:22.663158+00:00
[2024-07-04T21:46:24.083+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=7327) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-04T21:46:24.084+0000] {standard_task_runner.py:63} INFO - Started process 7329 to run task
[2024-07-04T21:46:24.084+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'podcast_summary', 'create_table_sqlite', 'manual__2024-07-04T21:46:22.663158+00:00', '--job-id', '117', '--raw', '--subdir', 'DAGS_FOLDER/podcast_summary.py', '--cfg-path', '/tmp/tmpdcckc6yi']
[2024-07-04T21:46:24.086+0000] {standard_task_runner.py:91} INFO - Job 117: Subtask create_table_sqlite
[2024-07-04T21:46:24.113+0000] {task_command.py:426} INFO - Running <TaskInstance: podcast_summary.create_table_sqlite manual__2024-07-04T21:46:22.663158+00:00 [running]> on host 4f6b501c5f6b
[2024-07-04T21:46:24.163+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='podcast_summary' AIRFLOW_CTX_TASK_ID='create_table_sqlite' AIRFLOW_CTX_EXECUTION_DATE='2024-07-04T21:46:22.663158+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-04T21:46:22.663158+00:00'
[2024-07-04T21:46:24.164+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-04T21:46:24.164+0000] {sql.py:276} INFO - Executing: 
        CREATE TABLE IF NOT EXISTS episodes(
            link TEXT PRIMARY KEY,
            title TEXT,
            filename Text,
            description Text
        )
    
[2024-07-04T21:46:24.168+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-04T21:46:24.171+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 277, in execute
    hook = self.get_db_hook()
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 188, in get_db_hook
    return self._hook
           ^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 995, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 150, in _hook
    conn = BaseHook.get_connection(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `sqlite_default` isn't defined
[2024-07-04T21:46:24.175+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=podcast_summary, task_id=create_table_sqlite, run_id=manual__2024-07-04T21:46:22.663158+00:00, execution_date=20240704T214622, start_date=20240704T214624, end_date=20240704T214624
[2024-07-04T21:46:24.179+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 117 for task create_table_sqlite (The conn_id `sqlite_default` isn't defined; 7329)
[2024-07-04T21:46:24.188+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-04T21:46:24.193+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1296: AirflowProviderDeprecationWarning: Call to deprecated class SqliteOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.)
  result = cls.__new__(cls)

[2024-07-04T21:46:24.198+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-04T21:46:24.200+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
