[2024-07-05T21:17:44.651+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-05T21:17:44.660+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: podcast_summary.load_episodes manual__2024-07-05T21:17:39.581905+00:00 [queued]>
[2024-07-05T21:17:44.664+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: podcast_summary.load_episodes manual__2024-07-05T21:17:39.581905+00:00 [queued]>
[2024-07-05T21:17:44.664+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-05T21:17:44.669+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): load_episodes> on 2024-07-05 21:17:39.581905+00:00
[2024-07-05T21:17:44.672+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=13881) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-05T21:17:44.673+0000] {standard_task_runner.py:63} INFO - Started process 13883 to run task
[2024-07-05T21:17:44.673+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'podcast_summary', 'load_episodes', 'manual__2024-07-05T21:17:39.581905+00:00', '--job-id', '130', '--raw', '--subdir', 'DAGS_FOLDER/podcast_summary.py', '--cfg-path', '/tmp/tmpwe1aw7d0']
[2024-07-05T21:17:44.675+0000] {standard_task_runner.py:91} INFO - Job 130: Subtask load_episodes
[2024-07-05T21:17:44.695+0000] {task_command.py:426} INFO - Running <TaskInstance: podcast_summary.load_episodes manual__2024-07-05T21:17:39.581905+00:00 [running]> on host 4f6b501c5f6b
[2024-07-05T21:17:44.754+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='podcast_summary' AIRFLOW_CTX_TASK_ID='load_episodes' AIRFLOW_CTX_EXECUTION_DATE='2024-07-05T21:17:39.581905+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-05T21:17:39.581905+00:00'
[2024-07-05T21:17:44.759+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-05T21:17:44.763+0000] {base.py:84} INFO - Using connection ID 'podcasts' for task execution.
[2024-07-05T21:17:44.776+0000] {base.py:84} INFO - Using connection ID 'podcasts' for task execution.
[2024-07-05T21:17:44.779+0000] {base.py:84} INFO - Using connection ID 'podcasts' for task execution.
[2024-07-05T21:17:44.780+0000] {sql.py:187} WARNING - Placeholder defined in Connection 'None' is not listed in 'DEFAULT_SQL_PLACEHOLDERS' and got ignored. Falling back to the default placeholder '?'.
[2024-07-05T21:17:44.782+0000] {sql.py:593} INFO - Done loading. Loaded a total of 1 rows into episodes
[2024-07-05T21:17:44.785+0000] {base.py:84} INFO - Using connection ID 'podcasts' for task execution.
[2024-07-05T21:17:44.787+0000] {base.py:84} INFO - Using connection ID 'podcasts' for task execution.
[2024-07-05T21:17:44.787+0000] {sql.py:187} WARNING - Placeholder defined in Connection 'None' is not listed in 'DEFAULT_SQL_PLACEHOLDERS' and got ignored. Falling back to the default placeholder '?'.
[2024-07-05T21:17:44.788+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-05T21:17:44.788+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/podcast_summary.py", line 54, in load_episodes
    hook.insert_rows(table="episodes", rows=new_episodes, target_fields=["link", "title", "published", "description", "filename"])
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 586, in insert_rows
    cur.execute(sql, values)
sqlite3.IntegrityError: UNIQUE constraint failed: episodes.link
[2024-07-05T21:17:44.792+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=podcast_summary, task_id=load_episodes, run_id=manual__2024-07-05T21:17:39.581905+00:00, execution_date=20240705T211739, start_date=20240705T211744, end_date=20240705T211744
[2024-07-05T21:17:44.797+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 130 for task load_episodes (UNIQUE constraint failed: episodes.link; 13883)
[2024-07-05T21:17:44.813+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-05T21:17:44.821+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-05T21:17:44.822+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
