[2024-07-04T19:40:50.972+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-04T19:40:50.982+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: podcast_summary.get_episodes manual__2024-07-04T19:40:48.521110+00:00 [queued]>
[2024-07-04T19:40:50.985+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: podcast_summary.get_episodes manual__2024-07-04T19:40:48.521110+00:00 [queued]>
[2024-07-04T19:40:50.986+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-04T19:40:50.991+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): get_episodes> on 2024-07-04 19:40:48.521110+00:00
[2024-07-04T19:40:50.996+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=5989) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-04T19:40:50.997+0000] {standard_task_runner.py:63} INFO - Started process 5991 to run task
[2024-07-04T19:40:50.997+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'podcast_summary', 'get_episodes', 'manual__2024-07-04T19:40:48.521110+00:00', '--job-id', '112', '--raw', '--subdir', 'DAGS_FOLDER/podcast_summary.py', '--cfg-path', '/tmp/tmp4d0dwyxa']
[2024-07-04T19:40:50.998+0000] {standard_task_runner.py:91} INFO - Job 112: Subtask get_episodes
[2024-07-04T19:40:51.024+0000] {task_command.py:426} INFO - Running <TaskInstance: podcast_summary.get_episodes manual__2024-07-04T19:40:48.521110+00:00 [running]> on host 4f6b501c5f6b
[2024-07-04T19:40:51.103+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='podcast_summary' AIRFLOW_CTX_TASK_ID='get_episodes' AIRFLOW_CTX_EXECUTION_DATE='2024-07-04T19:40:48.521110+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-04T19:40:48.521110+00:00'
[2024-07-04T19:40:51.107+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-04T19:40:51.359+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-04T19:40:51.359+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/podcast_summary.py", line 20, in get_episodes
    episodes = feed["rss"]["channel"]["item"]
               ~~~~^^^^^^^
KeyError: 'rss'
[2024-07-04T19:40:51.366+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=podcast_summary, task_id=get_episodes, run_id=manual__2024-07-04T19:40:48.521110+00:00, execution_date=20240704T194048, start_date=20240704T194050, end_date=20240704T194051
[2024-07-04T19:40:51.373+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 112 for task get_episodes ('rss'; 5991)
[2024-07-04T19:40:51.384+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-04T19:40:51.396+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-04T19:40:51.399+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
